services:
  webmushra:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs:/var/www/html/configs
      - ./results:/var/www/html/results
    ports:
      - "8080:80"
